export const CREATE_SUB_REQUEST = "CREATE_SUB_REQUEST";
export const CREATE_SUB_SUCCESS = "CREATE_SUB_SUCCESS";

export const GET_SUBS_REQUEST = "GET_SUBS_REQUEST";
export const GET_SUBS_SUCCESS = "GET_SUBS_SUCCESS";

export const DELETE_SUB_REQUEST = "DELETE_SUB_REQUEST";
export const DELETE_SUB_SUCCESS = "DELETE_SUB_SUCCESS";

export const GET_EVENTS_REQUEST = "GET_EVENTS_REQUEST";
export const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS";
